-- MySQL Script generated by MySQL Workbench
-- Wed Jan 10 17:47:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestionlab_schema` DEFAULT CHARACTER SET utf8 ;
USE `gestionlab_schema` ;

-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionlab_schema`.`person` (
  `id_person` INT NOT NULL AUTO_INCREMENT,
  `name_person` VARCHAR(45) NOT NULL,
  `lastname_person` VARCHAR(45) NOT NULL,
  `dni_person` VARCHAR(45) NOT NULL,
  `email_person` VARCHAR(45) NOT NULL,
  `number_person` VARCHAR(45) NOT NULL,
  `address_person` VARCHAR(45) NOT NULL,
  `birth_date_person` VARCHAR(45) NOT NULL,
  `emergency_number` VARCHAR(45) NOT NULL,
  `nationality_person` VARCHAR(45) NOT NULL,
  `gender_person` VARCHAR(45) NULL,
  PRIMARY KEY (`id_person`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionlab_schema`.`contract` (
  `id_contract` INT NOT NULL,
  `duration_contract` VARCHAR(45) NOT NULL COMMENT '\"indefinido\", \"temporal\", \"a plazo fijo\"',
  `hours_per_day` VARCHAR(45) NULL,
  `benefits_contract` VARCHAR(45) NULL COMMENT 'Lista de beneficios asociados con este tipo de contrato, como seguro médico, vacaciones pagadas, etc.',
  `start_day_contract` VARCHAR(45) NOT NULL,
  `special_requirements` VARCHAR(45) NULL COMMENT 'Cualquier requisito especial asociado con este tipo de contrato.',
  `bonuses_contract` VARCHAR(45) NULL,
  `description_comtract` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_contract`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`salary_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionlab_schema`.`salary_info` (
  `id_salary_info` INT NOT NULL,
  `base_salary` FLOAT NOT NULL,
  `bonuses` FLOAT NULL,
  PRIMARY KEY (`id_salary_info`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionlab_schema`.`schedule` (
  `id_schedule` INT NOT NULL,
  `day` VARCHAR(45) NOT NULL,
  `start_hour` VARCHAR(45) NOT NULL,
  `schedulecol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_schedule`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionlab_schema`.`employee` (
  `id_employee` INT UNSIGNED NOT NULL,
  `pass_employee` VARCHAR(45) NOT NULL,
  `permission_employee` VARCHAR(45) NOT NULL,
  `department_employee` VARCHAR(45) NOT NULL,
  `fk_person` INT NOT NULL,
  `fk_salary_info` INT NOT NULL,
  `fk_schedule` INT NOT NULL,
  `fk_contract` INT NOT NULL,
  PRIMARY KEY (`id_employee`, `fk_person`, `fk_salary_info`, `fk_schedule`, `fk_contract`),
  INDEX `fk_employee_person_idx` (`fk_person` ASC) VISIBLE,
  INDEX `fk_employee_contract1_idx` (`fk_contract` ASC) VISIBLE,
  INDEX `fk_employee_salary_info1_idx` (`fk_salary_info` ASC) VISIBLE,
  INDEX `fk_employee_schedule1_idx` (`fk_schedule` ASC) VISIBLE,
  CONSTRAINT `fk_employee_person`
    FOREIGN KEY (`fk_person`)
    REFERENCES `mydb`.`person` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_contract1`
    FOREIGN KEY (`fk_contract`)
    REFERENCES `mydb`.`contract` (`id_contract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_salary_info1`
    FOREIGN KEY (`fk_salary_info`)
    REFERENCES `mydb`.`salary_info` (`id_salary_info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_schedule1`
    FOREIGN KEY (`fk_schedule`)
    REFERENCES `mydb`.`schedule` (`id_schedule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`document_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionlab_schema`.`document_type` (
  `id_document_type` INT NOT NULL,
  `name_document_type` VARCHAR(45) NOT NULL,
  `description_document_type` VARCHAR(100) NULL,
  PRIMARY KEY (`id_document_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee_documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionlab_schema`.`employee_documents` (
  `id_employee_documents` INT NOT NULL,
  `name_document` VARCHAR(45) NOT NULL,
  `fk_document_type` INT NOT NULL,
  `fk_employee` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_employee_documents`, `fk_document_type`, `fk_employee`),
  INDEX `fk_employee_documents_document_type1_idx` (`fk_document_type` ASC) VISIBLE,
  INDEX `fk_employee_documents_employee1_idx` (`fk_employee` ASC) VISIBLE,
  CONSTRAINT `fk_employee_documents_document_type1`
    FOREIGN KEY (`fk_document_type`)
    REFERENCES `mydb`.`document_type` (`id_document_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_documents_employee1`
    FOREIGN KEY (`fk_employee`)
    REFERENCES `mydb`.`employee` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`absences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionlab_schema`.`absences` (
  `id_absences` INT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `reason_absence` VARCHAR(45) NOT NULL,
  `document_absence` VARCHAR(45) NULL,
  `fk_employee` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_absences`, `fk_employee`),
  INDEX `fk_absences_employee1_idx` (`fk_employee` ASC) VISIBLE,
  CONSTRAINT `fk_absences_employee1`
    FOREIGN KEY (`fk_employee`)
    REFERENCES `mydb`.`employee` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`remuneration_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionlab_schema`.`remuneration_record` (
  `id_remuneration_record` INT NOT NULL,
  `date_remuneration` DATETIME NOT NULL,
  `name_remuneration` VARCHAR(45) NOT NULL,
  `observation_remuneration` VARCHAR(45) NULL,
  `fk_salary_info` INT NOT NULL,
  PRIMARY KEY (`id_remuneration_record`, `fk_salary_info`),
  INDEX `fk_remuneration_record_salary_info1_idx` (`fk_salary_info` ASC) VISIBLE,
  CONSTRAINT `fk_remuneration_record_salary_info1`
    FOREIGN KEY (`fk_salary_info`)
    REFERENCES `mydb`.`salary_info` (`id_salary_info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`performance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionlab_schema`.`performance` (
  `id_performance` INT NOT NULL,
  `date_performance` VARCHAR(45) NOT NULL,
  `goals` VARCHAR(45) NULL,
  `teamwork` VARCHAR(45) NULL,
  `attitude` VARCHAR(45) NULL,
  `meeting_standards` VARCHAR(45) NULL,
  `puntuality` VARCHAR(45) NULL,
  `observation` VARCHAR(45) NULL,
  `fk_employee` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_performance`, `fk_employee`),
  INDEX `fk_performance_employee1_idx` (`fk_employee` ASC) VISIBLE,
  CONSTRAINT `fk_performance_employee1`
    FOREIGN KEY (`fk_employee`)
    REFERENCES `mydb`.`employee` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionlab_schema`.`request` (
  `id_request` INT NOT NULL,
  `date_request` DATE NOT NULL,
  `reason_request` VARCHAR(45) NOT NULL,
  `type_request` VARCHAR(45) NOT NULL,
  `explanation_request` VARCHAR(800) NULL,
  `document_license` VARCHAR(100) NULL,
  `fk_employee` INT NOT NULL,
  PRIMARY KEY (`id_request`, `fk_employee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`license_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionlab_schema`.`license_request` (
  `id_license_request` INT NOT NULL,
  `document` VARCHAR(45) NULL,
  PRIMARY KEY (`id_license_request`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
